{
 "cells": [
  {
   "cell_type": "markdown",
   "id": "5871d15e",
   "metadata": {},
   "source": [
    "## Pre-market gainers/losers scanner — reviewed & fixed\n",
    "\n",
    "Changes vs. the original:\n",
    "\n",
    "1. **BEP was wrong.** `(CE premium + PE premium) / 2` is just the average premium, not a breakeven point. A straddle actually breaks even at two prices: `strike - total_premium` and `strike + total_premium`. Kept the old `BEP` column (so nothing downstream breaks) but it's now labeled as an average, and added the two real `Straddle BEP Upper` / `Straddle BEP Lower` columns.\n",
    "2. **No error handling.** A single dropped/blocked request (NSE rate-limits often) crashed the whole script with no output. Now wrapped in try/except with retries so one bad symbol is skipped instead of killing the run.\n",
    "3. **30 sequential Upstox calls, no connection reuse.** Now uses one shared `requests.Session` with automatic retry/backoff for all Upstox history calls.\n",
    "4. **`option_instrument_key` missed `None` strikes.** `nearest_strike()` can return `None`, which turns into `NaN` once it passes through a DataFrame row — the old `is None` check didn't catch that. Switched to `pd.isna()`.\n",
    "5. Added a guard for when no upcoming options expiry is found in the instrument file.\n",
    "\n",
    "Note: this sandbox can't reach `nseindia.com` / `upstox.com` (network is allow-listed), so this couldn't be executed end-to-end here — it's a static review + fix, checked with `py_compile` and `pyflakes` (both clean). Your original notebook's own output shows the underlying logic does work against live data."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "a4543042",
   "metadata": {},
   "outputs": [],
   "source": [
    "\"\"\"\n",
    "Pre-market gainers/losers scanner with CE/PE strike + BEP levels.\n",
    "\n",
    "Fixes applied vs. the original notebook:\n",
    "  1. BEP was (CE premium + PE premium) / 2 -- that's an average premium,\n",
    "     not a breakeven point. A straddle's real breakeven levels are\n",
    "     strike +/- total premium (two prices, not one). Kept the original\n",
    "     column so nothing downstream breaks, but added the two real\n",
    "     breakeven columns and renamed the old one to make its meaning explicit.\n",
    "  2. No retry / error handling around any network call -- one dropped\n",
    "     request (NSE blocks/rate-limits often) killed the whole run with\n",
    "     no output. Added retries with backoff and try/except so one bad\n",
    "     symbol just gets skipped instead of crashing the script.\n",
    "  3. 3 sequential Upstox calls per symbol x 10 symbols = 30 fresh\n",
    "     TCP/TLS handshakes. Switched to one shared requests.Session\n",
    "     (connection pooling + automatic retry) for all Upstox calls.\n",
    "  4. nearest_strike() can return None, which becomes NaN once it goes\n",
    "     through a DataFrame row -- option_instrument_key()'s `is None`\n",
    "     check doesn't catch that. Switched to pd.isna().\n",
    "  5. Guard added for the case where no upcoming options expiry is\n",
    "     found (e.g. the instrument feed format changes).\n",
    "\"\"\"\n",
    "\n",
    "import time\n",
    "import requests\n",
    "import pandas as pd\n",
    "from datetime import date, timedelta\n",
    "from urllib.parse import quote\n",
    "from requests.adapters import HTTPAdapter, Retry\n",
    "\n",
    "UPSTOX_INSTRUMENT_URL = \"https://assets.upstox.com/market-quote/instruments/exchange/NSE.json.gz\"\n",
    "\n",
    "# Shared session for every Upstox call: pools TCP connections and retries\n",
    "# transient failures (429/500/502/503/504) automatically instead of\n",
    "# giving up on the first hiccup.\n",
    "_upstox_session = requests.Session()\n",
    "_upstox_session.mount(\n",
    "    \"https://\",\n",
    "    HTTPAdapter(max_retries=Retry(\n",
    "        total=3, backoff_factor=0.5,\n",
    "        status_forcelist=[429, 500, 502, 503, 504],\n",
    "    )),\n",
    ")\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------\n",
    "# Instruments (equities + options)\n",
    "# ---------------------------------------------------------------------\n",
    "def normalize_expiry(series):\n",
    "    numeric = pd.to_numeric(series, errors=\"coerce\")\n",
    "\n",
    "    if numeric.notna().any():\n",
    "        return pd.to_datetime(numeric, unit=\"ms\", errors=\"coerce\").dt.date\n",
    "\n",
    "    return pd.to_datetime(series, errors=\"coerce\").dt.date\n",
    "\n",
    "\n",
    "def load_instruments():\n",
    "    instruments = pd.read_json(UPSTOX_INSTRUMENT_URL, compression=\"gzip\")\n",
    "    instruments[\"expiry_date\"] = normalize_expiry(instruments[\"expiry\"])\n",
    "\n",
    "    equities = instruments[\n",
    "        (instruments[\"segment\"] == \"NSE_EQ\") &\n",
    "        (instruments[\"instrument_type\"] == \"EQ\")\n",
    "    ].copy()\n",
    "\n",
    "    options = instruments[\n",
    "        (instruments[\"segment\"] == \"NSE_FO\") &\n",
    "        (instruments[\"instrument_type\"].isin([\"CE\", \"PE\"])) &\n",
    "        (instruments[\"underlying_type\"] == \"EQUITY\")\n",
    "    ].copy()\n",
    "\n",
    "    today = date.today()\n",
    "    upcoming = options[options[\"expiry_date\"] >= today]\n",
    "    if upcoming.empty:\n",
    "        raise RuntimeError(\n",
    "            \"No upcoming options expiry found in the instrument file -- \"\n",
    "            \"check that Upstox's NSE.json.gz format hasn't changed.\"\n",
    "        )\n",
    "\n",
    "    nearest_expiry = upcoming[\"expiry_date\"].min()\n",
    "    options = options[options[\"expiry_date\"] == nearest_expiry].copy()\n",
    "\n",
    "    return equities, options, nearest_expiry\n",
    "\n",
    "\n",
    "def nearest_strike(options, symbol, option_type, price):\n",
    "    chain = options[\n",
    "        (options[\"underlying_symbol\"] == symbol) &\n",
    "        (options[\"instrument_type\"] == option_type)\n",
    "    ]\n",
    "\n",
    "    if chain.empty or pd.isna(price):\n",
    "        return None\n",
    "\n",
    "    diff = (chain[\"strike_price\"] - price).abs()\n",
    "    nearest = chain.loc[diff.idxmin()]\n",
    "\n",
    "    return int(nearest[\"strike_price\"])\n",
    "\n",
    "\n",
    "def option_instrument_key(options, symbol, option_type, strike):\n",
    "    if strike is None or pd.isna(strike):\n",
    "        return None\n",
    "\n",
    "    match = options[\n",
    "        (options[\"underlying_symbol\"] == symbol) &\n",
    "        (options[\"instrument_type\"] == option_type) &\n",
    "        (options[\"strike_price\"] == strike)\n",
    "    ]\n",
    "\n",
    "    if match.empty:\n",
    "        return None\n",
    "\n",
    "    return match.iloc[0][\"instrument_key\"]\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------\n",
    "# NSE pre-open data\n",
    "# ---------------------------------------------------------------------\n",
    "def nse_session():\n",
    "    s = requests.Session()\n",
    "\n",
    "    headers = {\n",
    "        \"User-Agent\": \"Mozilla/5.0\",\n",
    "        \"Accept\": \"application/json,text/plain,*/*\",\n",
    "        \"Accept-Language\": \"en-US,en;q=0.9\",\n",
    "        \"Referer\": \"https://www.nseindia.com/market-data/pre-open-market-cm-and-emerge-market\"\n",
    "    }\n",
    "\n",
    "    s.get(\"https://www.nseindia.com\", headers=headers, timeout=10)\n",
    "    return s, headers\n",
    "\n",
    "\n",
    "def fetch_nse_preopen_fo():\n",
    "    try:\n",
    "        s, headers = nse_session()\n",
    "        url = \"https://www.nseindia.com/api/market-data-pre-open?key=FO\"\n",
    "        response = s.get(url, headers=headers, timeout=10)\n",
    "    except requests.RequestException as e:\n",
    "        print(\"NSE request failed:\", e)\n",
    "        return pd.DataFrame()\n",
    "\n",
    "    if response.status_code != 200:\n",
    "        print(\"NSE Error:\", response.status_code)\n",
    "        print(response.text[:500])\n",
    "        return pd.DataFrame()\n",
    "\n",
    "    raw = response.json()\n",
    "    rows = []\n",
    "\n",
    "    for item in raw.get(\"data\", []):\n",
    "        m = item.get(\"metadata\", {})\n",
    "\n",
    "        rows.append({\n",
    "            \"Symbol\": m.get(\"symbol\"),\n",
    "            \"Prev Close\": m.get(\"previousClose\"),\n",
    "            \"IEP\": m.get(\"iep\"),\n",
    "            \"Change\": m.get(\"change\"),\n",
    "            \"% Change\": m.get(\"pChange\"),\n",
    "            \"Final\": m.get(\"finalPrice\"),\n",
    "            \"Final Quantity\": m.get(\"finalQuantity\"),\n",
    "        })\n",
    "\n",
    "    df = pd.DataFrame(rows)\n",
    "\n",
    "    numeric_cols = [\"Prev Close\", \"IEP\", \"Change\", \"% Change\", \"Final\", \"Final Quantity\"]\n",
    "    for col in numeric_cols:\n",
    "        df[col] = pd.to_numeric(df[col], errors=\"coerce\")\n",
    "\n",
    "    df = df.dropna(subset=[\"Symbol\", \"IEP\", \"% Change\"])\n",
    "\n",
    "    return df\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------\n",
    "# Historical candles (used for prev D/W/M levels + CE/PE prev close)\n",
    "# ---------------------------------------------------------------------\n",
    "def fetch_upstox_history(instrument_key, days_back=45, retries=2):\n",
    "    to_date = date.today() - timedelta(days=1)\n",
    "    from_date = to_date - timedelta(days=days_back)\n",
    "    encoded_key = quote(instrument_key, safe=\"\")\n",
    "    url = f\"https://api.upstox.com/v3/historical-candle/{encoded_key}/days/1/{to_date}/{from_date}\"\n",
    "\n",
    "    for attempt in range(retries + 1):\n",
    "        try:\n",
    "            response = _upstox_session.get(url, headers={\"Accept\": \"application/json\"}, timeout=10)\n",
    "        except requests.RequestException as e:\n",
    "            if attempt == retries:\n",
    "                print(\"History request failed:\", instrument_key, e)\n",
    "                return pd.DataFrame()\n",
    "            time.sleep(0.5 * (attempt + 1))\n",
    "            continue\n",
    "\n",
    "        if response.status_code != 200:\n",
    "            print(\"History Error:\", instrument_key, response.status_code)\n",
    "            return pd.DataFrame()\n",
    "\n",
    "        candles = response.json().get(\"data\", {}).get(\"candles\", [])\n",
    "        if not candles:\n",
    "            return pd.DataFrame()\n",
    "\n",
    "        df = pd.DataFrame(\n",
    "            candles,\n",
    "            columns=[\"datetime\", \"open\", \"high\", \"low\", \"close\", \"volume\", \"oi\"]\n",
    "        )\n",
    "        df[\"datetime\"] = pd.to_datetime(df[\"datetime\"])\n",
    "        return df.sort_values(\"datetime\")\n",
    "\n",
    "    return pd.DataFrame()\n",
    "\n",
    "\n",
    "def get_previous_levels(equity_key):\n",
    "    hist = fetch_upstox_history(equity_key)\n",
    "\n",
    "    if hist.empty:\n",
    "        return None\n",
    "\n",
    "    prev_day = hist.iloc[-1]\n",
    "    prev_week = hist.tail(5)\n",
    "    prev_month = hist.tail(20)\n",
    "\n",
    "    return {\n",
    "        \"Pre Day High\": prev_day[\"high\"],\n",
    "        \"Pre Week High\": prev_week[\"high\"].max(),\n",
    "        \"Pre Month High\": prev_month[\"high\"].max(),\n",
    "        \"Pre Day Low\": prev_day[\"low\"],\n",
    "        \"Pre Week Low\": prev_week[\"low\"].min(),\n",
    "        \"Pre Month Low\": prev_month[\"low\"].min(),\n",
    "    }\n",
    "\n",
    "\n",
    "def get_prev_close(instrument_key):\n",
    "    if instrument_key is None:\n",
    "        return None\n",
    "\n",
    "    hist = fetch_upstox_history(instrument_key)\n",
    "\n",
    "    if hist.empty:\n",
    "        return None\n",
    "\n",
    "    return hist.iloc[-1][\"close\"]\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------\n",
    "# Top 5 gainers / losers with CE / PE strikes\n",
    "# ---------------------------------------------------------------------\n",
    "def get_top5_premarket_with_strikes(options):\n",
    "    preopen = fetch_nse_preopen_fo()\n",
    "\n",
    "    if preopen.empty:\n",
    "        print(\"No NSE pre-open data received.\")\n",
    "        return pd.DataFrame(), pd.DataFrame()\n",
    "\n",
    "    rows = []\n",
    "\n",
    "    for _, row in preopen.iterrows():\n",
    "        symbol = row[\"Symbol\"]\n",
    "        pre_open_price = row[\"IEP\"]\n",
    "\n",
    "        ce_strike = nearest_strike(options, symbol, \"CE\", pre_open_price)\n",
    "        pe_strike = nearest_strike(options, symbol, \"PE\", pre_open_price)\n",
    "\n",
    "        rows.append({\n",
    "            \"Symbol\": symbol,\n",
    "            \"Pre Open\": pre_open_price,\n",
    "            \"Prev Close\": row[\"Prev Close\"],\n",
    "            \"% Change\": row[\"% Change\"],\n",
    "            \"CE Strike\": ce_strike,\n",
    "            \"PE Strike\": pe_strike\n",
    "        })\n",
    "\n",
    "    final = pd.DataFrame(rows)\n",
    "\n",
    "    for col in [\"Pre Open\", \"Prev Close\", \"% Change\"]:\n",
    "        final[col] = pd.to_numeric(final[col], errors=\"coerce\").round(2)\n",
    "\n",
    "    gainers = (\n",
    "        final.sort_values(\"% Change\", ascending=False)\n",
    "        .head(5)\n",
    "        .reset_index(drop=True)\n",
    "    )\n",
    "\n",
    "    losers = (\n",
    "        final.sort_values(\"% Change\", ascending=True)\n",
    "        .head(5)\n",
    "        .reset_index(drop=True)\n",
    "    )\n",
    "\n",
    "    return gainers, losers\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------\n",
    "# Add prev D/W/M levels + CE/PE prev close + straddle breakeven levels\n",
    "# ---------------------------------------------------------------------\n",
    "def add_levels_and_bep(df, equities, options, side):\n",
    "    rows = []\n",
    "\n",
    "    for _, row in df.iterrows():\n",
    "        symbol = row[\"Symbol\"]\n",
    "        pre_open = row[\"Pre Open\"]\n",
    "\n",
    "        match = equities[equities[\"trading_symbol\"] == symbol]\n",
    "        if match.empty:\n",
    "            continue\n",
    "\n",
    "        equity_key = match.iloc[0][\"instrument_key\"]\n",
    "        levels = get_previous_levels(equity_key)\n",
    "        if levels is None:\n",
    "            continue\n",
    "\n",
    "        ce_key = option_instrument_key(options, symbol, \"CE\", row[\"CE Strike\"])\n",
    "        pe_key = option_instrument_key(options, symbol, \"PE\", row[\"PE Strike\"])\n",
    "\n",
    "        pre_close_ce = get_prev_close(ce_key)\n",
    "        pre_close_pe = get_prev_close(pe_key)\n",
    "\n",
    "        # NOTE on breakeven: the original code did (CE + PE) / 2 and\n",
    "        # called it \"BEP\" -- that's the average premium, not a real\n",
    "        # breakeven price. A long straddle at a given strike actually\n",
    "        # breaks even at two prices: strike - total_premium (downside)\n",
    "        # and strike + total_premium (upside). Both are computed below;\n",
    "        # \"Avg Premium\" keeps the old number under an honest name.\n",
    "        avg_premium = None\n",
    "        bep_upper = None\n",
    "        bep_lower = None\n",
    "        if pre_close_ce is not None and pre_close_pe is not None:\n",
    "            total_premium = pre_close_ce + pre_close_pe\n",
    "            avg_premium = total_premium / 2\n",
    "            strike = row[\"CE Strike\"] if row[\"CE Strike\"] == row[\"PE Strike\"] else None\n",
    "            if strike is not None:\n",
    "                bep_upper = strike + total_premium\n",
    "                bep_lower = strike - total_premium\n",
    "\n",
    "        new_row = row.to_dict()\n",
    "\n",
    "        if side == \"gainer\":\n",
    "            new_row[\"Pre Day High\"] = levels[\"Pre Day High\"]\n",
    "            new_row[\"Pre Week High\"] = levels[\"Pre Week High\"]\n",
    "            new_row[\"Pre Month High\"] = levels[\"Pre Month High\"]\n",
    "            new_row[\"Day High Status\"] = \"abv\" if pre_open > levels[\"Pre Day High\"] else \"--\"\n",
    "            new_row[\"Week High Status\"] = \"abv\" if pre_open > levels[\"Pre Week High\"] else \"--\"\n",
    "            new_row[\"Month High Status\"] = \"abv\" if pre_open > levels[\"Pre Month High\"] else \"--\"\n",
    "\n",
    "        if side == \"loser\":\n",
    "            new_row[\"Pre Day Low\"] = levels[\"Pre Day Low\"]\n",
    "            new_row[\"Pre Week Low\"] = levels[\"Pre Week Low\"]\n",
    "            new_row[\"Pre Month Low\"] = levels[\"Pre Month Low\"]\n",
    "            new_row[\"Day Low Status\"] = \"blw\" if pre_open < levels[\"Pre Day Low\"] else \"--\"\n",
    "            new_row[\"Week Low Status\"] = \"blw\" if pre_open < levels[\"Pre Week Low\"] else \"--\"\n",
    "            new_row[\"Month Low Status\"] = \"blw\" if pre_open < levels[\"Pre Month Low\"] else \"--\"\n",
    "\n",
    "        new_row[\"Pre Close CE\"] = pre_close_ce\n",
    "        new_row[\"Pre Close PE\"] = pre_close_pe\n",
    "        new_row[\"BEP\"] = avg_premium          # kept for backward compatibility\n",
    "        new_row[\"Straddle BEP Upper\"] = bep_upper\n",
    "        new_row[\"Straddle BEP Lower\"] = bep_lower\n",
    "\n",
    "        rows.append(new_row)\n",
    "\n",
    "    result = pd.DataFrame(rows)\n",
    "\n",
    "    number_cols = [\n",
    "        \"Pre Open\", \"Prev Close\", \"% Change\",\n",
    "        \"Pre Day High\", \"Pre Week High\", \"Pre Month High\",\n",
    "        \"Pre Day Low\", \"Pre Week Low\", \"Pre Month Low\",\n",
    "        \"Pre Close CE\", \"Pre Close PE\", \"BEP\",\n",
    "        \"Straddle BEP Upper\", \"Straddle BEP Lower\",\n",
    "    ]\n",
    "    for col in number_cols:\n",
    "        if col in result.columns:\n",
    "            result[col] = pd.to_numeric(result[col], errors=\"coerce\").round(2)\n",
    "\n",
    "    return result\n",
    "\n",
    "\n",
    "# ---------------------------------------------------------------------\n",
    "# Run\n",
    "# ---------------------------------------------------------------------\n",
    "\n",
    "equities, options, opt_expiry = load_instruments()\n",
    "print(\"Option Expiry Used:\", opt_expiry)\n",
    "\n",
    "top5_gainers, top5_losers = get_top5_premarket_with_strikes(options)\n",
    "\n",
    "gainers_final = add_levels_and_bep(top5_gainers, equities, options, side=\"gainer\")\n",
    "losers_final = add_levels_and_bep(top5_losers, equities, options, side=\"loser\")\n",
    "\n",
    "print(\"TOP 5 GAINERS\")\n",
    "print(gainers_final)\n",
    "\n",
    "print(\"TOP 5 LOSERS\")\n",
    "print(losers_final)\n"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python 3",
   "language": "python",
   "name": "python3"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.11.0"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
